apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 5m
  path: ./part4/project
  prune: true
  validation: client